version: '3.8'

services:
  backend:
    build:
      context: ./back
    ports:
      - "3004:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_DATABASE: TrelloClone
      JWT_SECRET: MYPASSWORD
    env_file:
      - ./back/.env

  frontend:
    build:
      context: ./front
    ports:
      - "9070:80"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: MYPASSWORD
      POSTGRES_DB: TrelloClone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
